package org.mulesoft.hospitality.oracle.oracleowsmock;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Default SpringBootApplication class as generated by Spring Initializr.
 *
 * @author  Alan Belisle
 */
@SpringBootApplication
public class OracleOwsMockApplication {

	public static void main(String[] args) {
		SpringApplication.run(OracleOwsMockApplication.class, args);
	}

}
